#[derive(Debug, Clone)]
pub(crate) struct PendingNetworkSelectorReturn {
    pub(crate) selector: String,
    pub(crate) receiver: u32,
    pub(crate) arg2: u32,
    pub(crate) arg3: u32,
    pub(crate) aux: u32,
    pub(crate) return_pc: u32,
    pub(crate) return_thumb: bool,
    pub(crate) dispatch_pc: u32,
}

#[derive(Debug, Clone)]
pub(crate) struct NetworkState {
    network_delegate: u32,
    reachability: u32,
    network_url: u32,
    network_request: u32,
    network_connection: u32,
    network_response: u32,
    network_data: u32,
    proxy_settings: u32,
    fault_connection: u32,
    network_error: u32,
    read_stream: u32,
    write_stream: u32,
    reachability_scheduled: bool,
    reachability_callback_set: bool,
    read_stream_open: bool,
    read_stream_scheduled: bool,
    read_stream_client_set: bool,
    read_stream_client_flags: u32,
    read_stream_client_callback: u32,
    read_stream_client_context: u32,
    write_stream_open: bool,
    write_stream_scheduled: bool,
    write_stream_client_set: bool,
    write_stream_client_flags: u32,
    write_stream_client_callback: u32,
    write_stream_client_context: u32,
    network_armed: bool,
    network_completed: bool,
    network_stage: u32,
    network_events: u32,
    delegate_callbacks: u32,
    reachability_flags: u32,
    read_stream_status: u32,
    write_stream_status: u32,
    read_stream_events: u32,
    write_stream_events: u32,
    read_stream_bytes_consumed: u32,
    write_stream_bytes_written: u32,
    network_bytes_delivered: u32,
    network_source_closed: bool,
    network_response_retained: bool,
    network_data_retained: bool,
    network_error_retained: bool,
    network_timeout_armed: bool,
    network_faulted: bool,
    network_cancelled: bool,
    network_fault_events: u32,
    network_fault_mode: u32,
    network_fault_history: Vec<String>,
    network_delegate_binding_trace: Vec<String>,
    network_connection_birth_trace: Vec<String>,
    network_slot_trace: Vec<String>,
    network_owner_candidate_trace: Vec<String>,
    network_last_delegate_binding: Option<String>,
    network_last_connection_birth: Option<String>,
    network_last_slot_event: Option<String>,
    network_last_owner_candidate: Option<String>,
    first_app_delegate_binding: Option<String>,
    network_seed_trace_emitted: bool,
    pending_selector_returns: Vec<PendingNetworkSelectorReturn>,
}

impl Default for NetworkState {
    fn default() -> Self {
        Self {
            network_delegate: HLE_FAKE_APP_DELEGATE,
            reachability: HLE_FAKE_REACHABILITY,
            network_url: HLE_FAKE_URL,
            network_request: HLE_FAKE_URL_REQUEST,
            network_connection: HLE_FAKE_URL_CONNECTION,
            network_response: HLE_FAKE_HTTP_RESPONSE,
            network_data: HLE_FAKE_DATA,
            proxy_settings: HLE_FAKE_PROXY_SETTINGS,
            fault_connection: HLE_FAKE_FAULT_CONNECTION,
            network_error: HLE_FAKE_NETWORK_ERROR,
            read_stream: HLE_FAKE_READ_STREAM,
            write_stream: HLE_FAKE_WRITE_STREAM,
            reachability_scheduled: false,
            reachability_callback_set: false,
            read_stream_open: false,
            read_stream_scheduled: false,
            read_stream_client_set: false,
            read_stream_client_flags: 0,
            read_stream_client_callback: 0,
            read_stream_client_context: 0,
            write_stream_open: false,
            write_stream_scheduled: false,
            write_stream_client_set: false,
            write_stream_client_flags: 0,
            write_stream_client_callback: 0,
            write_stream_client_context: 0,
            network_armed: false,
            network_completed: false,
            network_stage: 0,
            network_events: 0,
            delegate_callbacks: 0,
            reachability_flags: 0x0000_0007,
            read_stream_status: 0,
            write_stream_status: 0,
            read_stream_events: 0,
            write_stream_events: 0,
            read_stream_bytes_consumed: 0,
            write_stream_bytes_written: 0,
            network_bytes_delivered: 0,
            network_source_closed: false,
            network_response_retained: false,
            network_data_retained: false,
            network_error_retained: false,
            network_timeout_armed: false,
            network_faulted: false,
            network_cancelled: false,
            network_fault_events: 0,
            network_fault_mode: 0,
            network_fault_history: Vec::new(),
            network_delegate_binding_trace: Vec::new(),
            network_connection_birth_trace: Vec::new(),
            network_slot_trace: Vec::new(),
            network_owner_candidate_trace: Vec::new(),
            network_last_delegate_binding: None,
            network_last_connection_birth: None,
            network_last_slot_event: None,
            network_last_owner_candidate: None,
            first_app_delegate_binding: None,
            network_seed_trace_emitted: false,
            pending_selector_returns: Vec::new(),
        }
    }
}
