use std::collections::HashMap;

#[derive(Debug, Clone)]
pub(crate) struct PendingSchedulerReturn {
    pub(crate) selector: String,
    pub(crate) receiver: u32,
    pub(crate) arg2: u32,
    pub(crate) arg3: u32,
    pub(crate) return_pc: u32,
    pub(crate) return_thumb: bool,
    pub(crate) presents_before: u32,
    pub(crate) frame_before: u32,
    pub(crate) dispatch_pc: u32,
}

#[derive(Debug, Clone)]
pub(crate) struct CocosState {
    synthetic_display_link: u32,
    cocos_director: u32,
    pub(crate) opengl_view: u32,
    running_scene: u32,
    next_scene: u32,
    effect_scene: u32,
    director_ivar_sync_inflight: bool,
    display_link_armed: bool,
    animation_running: bool,
    display_fps_enabled: bool,
    scene_transition_calls: u32,
    scene_run_with_scene_calls: u32,
    scene_replace_scene_calls: u32,
    scene_push_scene_calls: u32,
    scene_on_enter_events: u32,
    scene_on_exit_events: u32,
    scene_on_enter_transition_finish_events: u32,
    scene_handoff_pending: bool,
    scene_handoff_selector: Option<String>,
    scene_handoff_wait_ticks: u32,
    pending_scene_route_class: u32,
    pending_scene_route_owner: u32,
    pending_scene_route_selector: Option<String>,
    pending_scene_route_destination: u32,
    scene_instances_by_class: HashMap<u32, u32>,
    scene_stack: Vec<u32>,
    scene_recent_events: Vec<String>,
    scheduler_mainloop_calls: u32,
    scheduler_draw_scene_calls: u32,
    scheduler_draw_frame_calls: u32,
    scheduler_schedule_calls: u32,
    scheduler_update_calls: u32,
    scheduler_invalidate_calls: u32,
    scheduler_render_callback_calls: u32,
    scheduler_recent_events: Vec<String>,
    director_type: u32,
    animation_interval_bits: u32,
    pending_scheduler_returns: Vec<PendingSchedulerReturn>,
}

impl Default for CocosState {
    fn default() -> Self {
        Self {
            synthetic_display_link: HLE_FAKE_SYNTH_DISPLAYLINK,
            cocos_director: 0,
            opengl_view: 0,
            running_scene: 0,
            next_scene: 0,
            effect_scene: 0,
            director_ivar_sync_inflight: false,
            display_link_armed: false,
            animation_running: false,
            display_fps_enabled: false,
            scene_transition_calls: 0,
            scene_run_with_scene_calls: 0,
            scene_replace_scene_calls: 0,
            scene_push_scene_calls: 0,
            scene_on_enter_events: 0,
            scene_on_exit_events: 0,
            scene_on_enter_transition_finish_events: 0,
            scene_handoff_pending: false,
            scene_handoff_selector: None,
            scene_handoff_wait_ticks: 0,
            pending_scene_route_class: 0,
            pending_scene_route_owner: 0,
            pending_scene_route_selector: None,
            pending_scene_route_destination: 0,
            scene_instances_by_class: HashMap::new(),
            scene_stack: Vec::new(),
            scene_recent_events: Vec::new(),
            scheduler_mainloop_calls: 0,
            scheduler_draw_scene_calls: 0,
            scheduler_draw_frame_calls: 0,
            scheduler_schedule_calls: 0,
            scheduler_update_calls: 0,
            scheduler_invalidate_calls: 0,
            scheduler_render_callback_calls: 0,
            scheduler_recent_events: Vec::new(),
            director_type: 0,
            animation_interval_bits: 0,
            pending_scheduler_returns: Vec::new(),
        }
    }
}
