#[derive(Debug, Clone)]
pub(crate) struct GraphicsState {
    eagl_context: u32,
    eagl_layer: u32,
    gl_framebuffer: u32,
    gl_renderbuffer: u32,
    pub(crate) graphics_context_current: bool,
    pub(crate) graphics_layer_attached: bool,
    graphics_surface_ready: bool,
    graphics_framebuffer_complete: bool,
    graphics_viewport_ready: bool,
    pub(crate) graphics_presented: bool,
    graphics_readback_ready: bool,
    graphics_frame_index: u32,
    graphics_present_calls: u32,
    graphics_draw_calls: u32,
    graphics_clear_calls: u32,
    graphics_readback_calls: u32,
    graphics_gl_calls: u32,
    graphics_last_error: u32,
    graphics_surface_width: u32,
    graphics_surface_height: u32,
    graphics_viewport_x: u32,
    graphics_viewport_y: u32,
    graphics_viewport_width: u32,
    graphics_viewport_height: u32,
    graphics_scissor_enabled: bool,
    graphics_scissor_x: u32,
    graphics_scissor_y: u32,
    graphics_scissor_width: u32,
    graphics_scissor_height: u32,
    graphics_framebuffer_bytes: u32,
    graphics_last_readback_bytes: u32,
    graphics_last_readback_x: u32,
    graphics_last_readback_y: u32,
    graphics_last_readback_width: u32,
    graphics_last_readback_height: u32,
    graphics_dump_saved: u32,
    graphics_last_dump_path: Option<String>,
    graphics_last_raw_dump_path: Option<String>,
    graphics_last_bgra_dump_path: Option<String>,
    graphics_last_viewport_tl_dump_path: Option<String>,
    graphics_last_viewport_bl_dump_path: Option<String>,
    graphics_last_bbox_dump_path: Option<String>,
    graphics_last_readback_checksum: u32,
    graphics_last_readback_origin: Option<String>,
    graphics_last_present_source: Option<String>,
    graphics_last_present_decision: Option<String>,
    graphics_last_visible_bbox_x: u32,
    graphics_last_visible_bbox_y: u32,
    graphics_last_visible_bbox_width: u32,
    graphics_last_visible_bbox_height: u32,
    graphics_last_visible_pixels: u32,
    graphics_last_nonzero_pixels: u32,
    graphics_diagnosis_hint: Option<String>,
    graphics_recent_events: Vec<String>,
    graphics_readback_changed: bool,
    graphics_readback_stable_streak: u32,
    graphics_last_dominant_rgba: Option<String>,
    graphics_last_dominant_pct_milli: u32,
    graphics_unique_frames_saved: u32,
    graphics_last_unique_dump_path: Option<String>,
    graphics_retained_present_calls: u32,
    graphics_synthetic_fallback_present_calls: u32,
    graphics_auto_scene_present_calls: u32,
    graphics_guest_draw_calls: u32,
    graphics_guest_vertex_fetches: u32,
    graphics_last_draw_mode: u32,
    graphics_last_draw_mode_label: Option<String>,
    graphics_last_guest_draw_checksum: u32,
    graphics_uikit_contexts_created: u32,
    graphics_uikit_images_created: u32,
    graphics_uikit_draw_ops: u32,
    graphics_uikit_present_ops: u32,
    graphics_last_ui_source: Option<String>,
    graphics_matrices: GraphicsMatrixStackState,
}

impl Default for GraphicsState {
    fn default() -> Self {
        Self {
            eagl_context: HLE_FAKE_EAGL_CONTEXT,
            eagl_layer: HLE_FAKE_CAEAGL_LAYER,
            gl_framebuffer: HLE_FAKE_GL_FRAMEBUFFER,
            gl_renderbuffer: HLE_FAKE_GL_RENDERBUFFER,
            graphics_context_current: false,
            graphics_layer_attached: false,
            graphics_surface_ready: false,
            graphics_framebuffer_complete: false,
            graphics_viewport_ready: false,
            graphics_presented: false,
            graphics_readback_ready: false,
            graphics_frame_index: 0,
            graphics_present_calls: 0,
            graphics_draw_calls: 0,
            graphics_clear_calls: 0,
            graphics_readback_calls: 0,
            graphics_gl_calls: 0,
            graphics_last_error: 0,
            graphics_surface_width: 320,
            graphics_surface_height: 480,
            graphics_viewport_x: 0,
            graphics_viewport_y: 0,
            graphics_viewport_width: 0,
            graphics_viewport_height: 0,
            graphics_scissor_enabled: false,
            graphics_scissor_x: 0,
            graphics_scissor_y: 0,
            graphics_scissor_width: 0,
            graphics_scissor_height: 0,
            graphics_framebuffer_bytes: 0,
            graphics_last_readback_bytes: 0,
            graphics_last_readback_x: 0,
            graphics_last_readback_y: 0,
            graphics_last_readback_width: 0,
            graphics_last_readback_height: 0,
            graphics_dump_saved: 0,
            graphics_last_dump_path: None,
            graphics_last_raw_dump_path: None,
            graphics_last_bgra_dump_path: None,
            graphics_last_viewport_tl_dump_path: None,
            graphics_last_viewport_bl_dump_path: None,
            graphics_last_bbox_dump_path: None,
            graphics_last_readback_checksum: 0,
            graphics_last_readback_origin: None,
            graphics_last_present_source: None,
            graphics_last_present_decision: None,
            graphics_last_visible_bbox_x: 0,
            graphics_last_visible_bbox_y: 0,
            graphics_last_visible_bbox_width: 0,
            graphics_last_visible_bbox_height: 0,
            graphics_last_visible_pixels: 0,
            graphics_last_nonzero_pixels: 0,
            graphics_diagnosis_hint: None,
            graphics_recent_events: Vec::new(),
            graphics_readback_changed: false,
            graphics_readback_stable_streak: 0,
            graphics_last_dominant_rgba: None,
            graphics_last_dominant_pct_milli: 0,
            graphics_unique_frames_saved: 0,
            graphics_last_unique_dump_path: None,
            graphics_retained_present_calls: 0,
            graphics_synthetic_fallback_present_calls: 0,
            graphics_auto_scene_present_calls: 0,
            graphics_guest_draw_calls: 0,
            graphics_guest_vertex_fetches: 0,
            graphics_last_draw_mode: 0,
            graphics_last_draw_mode_label: None,
            graphics_last_guest_draw_checksum: 0,
            graphics_uikit_contexts_created: 0,
            graphics_uikit_images_created: 0,
            graphics_uikit_draw_ops: 0,
            graphics_uikit_present_ops: 0,
            graphics_last_ui_source: None,
            graphics_matrices: GraphicsMatrixStackState::default(),
        }
    }
}

#[derive(Debug, Clone)]
pub(crate) struct NetworkState {
    network_delegate: u32,
    reachability: u32,
    network_url: u32,
    network_request: u32,
    network_connection: u32,
    network_response: u32,
    network_data: u32,
    proxy_settings: u32,
    fault_connection: u32,
    network_error: u32,
    read_stream: u32,
    write_stream: u32,
    reachability_scheduled: bool,
    reachability_callback_set: bool,
    read_stream_open: bool,
    read_stream_scheduled: bool,
    read_stream_client_set: bool,
    read_stream_client_flags: u32,
    read_stream_client_callback: u32,
    read_stream_client_context: u32,
    write_stream_open: bool,
    write_stream_scheduled: bool,
    write_stream_client_set: bool,
    write_stream_client_flags: u32,
    write_stream_client_callback: u32,
    write_stream_client_context: u32,
    network_armed: bool,
    network_completed: bool,
    network_stage: u32,
    network_events: u32,
    delegate_callbacks: u32,
    reachability_flags: u32,
    read_stream_status: u32,
    write_stream_status: u32,
    read_stream_events: u32,
    write_stream_events: u32,
    read_stream_bytes_consumed: u32,
    write_stream_bytes_written: u32,
    network_bytes_delivered: u32,
    network_source_closed: bool,
    network_response_retained: bool,
    network_data_retained: bool,
    network_error_retained: bool,
    network_timeout_armed: bool,
    network_faulted: bool,
    network_cancelled: bool,
    network_fault_events: u32,
    network_fault_mode: u32,
    network_fault_history: Vec<String>,
    network_delegate_binding_trace: Vec<String>,
    network_connection_birth_trace: Vec<String>,
    network_last_delegate_binding: Option<String>,
    network_last_connection_birth: Option<String>,
}

impl Default for NetworkState {
    fn default() -> Self {
        Self {
            network_delegate: HLE_FAKE_APP_DELEGATE,
            reachability: HLE_FAKE_REACHABILITY,
            network_url: HLE_FAKE_URL,
            network_request: HLE_FAKE_URL_REQUEST,
            network_connection: HLE_FAKE_URL_CONNECTION,
            network_response: HLE_FAKE_HTTP_RESPONSE,
            network_data: HLE_FAKE_DATA,
            proxy_settings: HLE_FAKE_PROXY_SETTINGS,
            fault_connection: HLE_FAKE_FAULT_CONNECTION,
            network_error: HLE_FAKE_NETWORK_ERROR,
            read_stream: HLE_FAKE_READ_STREAM,
            write_stream: HLE_FAKE_WRITE_STREAM,
            reachability_scheduled: false,
            reachability_callback_set: false,
            read_stream_open: false,
            read_stream_scheduled: false,
            read_stream_client_set: false,
            read_stream_client_flags: 0,
            read_stream_client_callback: 0,
            read_stream_client_context: 0,
            write_stream_open: false,
            write_stream_scheduled: false,
            write_stream_client_set: false,
            write_stream_client_flags: 0,
            write_stream_client_callback: 0,
            write_stream_client_context: 0,
            network_armed: false,
            network_completed: false,
            network_stage: 0,
            network_events: 0,
            delegate_callbacks: 0,
            reachability_flags: 0x0000_0007,
            read_stream_status: 0,
            write_stream_status: 0,
            read_stream_events: 0,
            write_stream_events: 0,
            read_stream_bytes_consumed: 0,
            write_stream_bytes_written: 0,
            network_bytes_delivered: 0,
            network_source_closed: false,
            network_response_retained: false,
            network_data_retained: false,
            network_error_retained: false,
            network_timeout_armed: false,
            network_faulted: false,
            network_cancelled: false,
            network_fault_events: 0,
            network_fault_mode: 0,
            network_fault_history: Vec::new(),
            network_delegate_binding_trace: Vec::new(),
            network_connection_birth_trace: Vec::new(),
            network_last_delegate_binding: None,
            network_last_connection_birth: None,
        }
    }
}

#[derive(Debug, Clone)]
pub(crate) struct CocosState {
    synthetic_display_link: u32,
    cocos_director: u32,
    pub(crate) opengl_view: u32,
    running_scene: u32,
    display_link_armed: bool,
    animation_running: bool,
    display_fps_enabled: bool,
    scene_transition_calls: u32,
    scene_run_with_scene_calls: u32,
    scene_replace_scene_calls: u32,
    scene_push_scene_calls: u32,
    scene_on_enter_events: u32,
    scene_on_exit_events: u32,
    scene_on_enter_transition_finish_events: u32,
    scene_recent_events: Vec<String>,
    scheduler_mainloop_calls: u32,
    scheduler_draw_scene_calls: u32,
    scheduler_draw_frame_calls: u32,
    scheduler_schedule_calls: u32,
    scheduler_update_calls: u32,
    scheduler_invalidate_calls: u32,
    scheduler_render_callback_calls: u32,
    scheduler_recent_events: Vec<String>,
    director_type: u32,
    animation_interval_bits: u32,
}

impl Default for CocosState {
    fn default() -> Self {
        Self {
            synthetic_display_link: HLE_FAKE_SYNTH_DISPLAYLINK,
            cocos_director: 0,
            opengl_view: 0,
            running_scene: 0,
            display_link_armed: false,
            animation_running: false,
            display_fps_enabled: false,
            scene_transition_calls: 0,
            scene_run_with_scene_calls: 0,
            scene_replace_scene_calls: 0,
            scene_push_scene_calls: 0,
            scene_on_enter_events: 0,
            scene_on_exit_events: 0,
            scene_on_enter_transition_finish_events: 0,
            scene_recent_events: Vec::new(),
            scheduler_mainloop_calls: 0,
            scheduler_draw_scene_calls: 0,
            scheduler_draw_frame_calls: 0,
            scheduler_schedule_calls: 0,
            scheduler_update_calls: 0,
            scheduler_invalidate_calls: 0,
            scheduler_render_callback_calls: 0,
            scheduler_recent_events: Vec::new(),
            director_type: 0,
            animation_interval_bits: 0,
        }
    }
}

#[derive(Debug, Clone)]
pub(crate) struct UIKitObjectState {
    app: u32,
    delegate: u32,
    window: u32,
    root_controller: u32,
    screen: u32,
    main_runloop: u32,
    default_mode: u32,
    synthetic_timer: u32,
    first_responder: u32,
    view_superviews: std::collections::HashMap<u32, u32>,
    view_subviews: std::collections::HashMap<u32, Vec<u32>>,
}

impl Default for UIKitObjectState {
    fn default() -> Self {
        Self {
            app: HLE_FAKE_UIAPPLICATION,
            delegate: HLE_FAKE_APP_DELEGATE,
            window: HLE_FAKE_UIWINDOW,
            root_controller: HLE_FAKE_ROOT_CONTROLLER,
            screen: HLE_FAKE_MAIN_SCREEN,
            main_runloop: HLE_FAKE_MAIN_RUNLOOP,
            default_mode: HLE_FAKE_DEFAULT_MODE,
            synthetic_timer: HLE_FAKE_SYNTH_TIMER,
            first_responder: HLE_FAKE_ROOT_CONTROLLER,
            view_superviews: std::collections::HashMap::new(),
            view_subviews: std::collections::HashMap::new(),
        }
    }
}

#[derive(Debug, Clone, Default)]
pub(crate) struct UIKitRuntimeState {
    launched: bool,
    delegate_set: bool,
    pub(crate) window_visible: bool,
    app_active: bool,
    runloop_live: bool,
    timer_armed: bool,
    exit_suppressed: bool,
    launch_count: u32,
    activation_count: u32,
    runloop_ticks: u32,
    runloop_sources: u32,
    last_tick_sources_before: u32,
    last_tick_sources_after: u32,
    idle_ticks_after_completion: u32,
}

#[derive(Debug, Clone, Default)]
pub(crate) struct UIKitState {
    pub(crate) objects: UIKitObjectState,
    pub(crate) runtime: UIKitRuntimeState,
    pub(crate) graphics: GraphicsState,
    pub(crate) network: NetworkState,
    pub(crate) cocos: CocosState,
}
