use serde::{Deserialize, Serialize};

use super::synthetic::RuntimeSyntheticConfigReport;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RuntimeUiSummary {
    pub launched: bool,
    pub delegate_set: bool,
    pub window_visible: bool,
    pub app_active: bool,
    pub runloop_live: bool,
    pub exit_suppressed: bool,
    pub launch_count: u32,
    pub activation_count: u32,
    pub cocos_director: Option<u32>,
    pub opengl_view: Option<u32>,
    pub running_scene: Option<u32>,
    pub director_type: u32,
    pub animation_running: bool,
    pub display_fps_enabled: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RuntimeRunloopSummary {
    pub ticks: u32,
    pub sources: u32,
    pub last_tick_sources_before: u32,
    pub last_tick_sources_after: u32,
    pub idle_ticks_after_completion: u32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RuntimeInputSummary {
    pub queued: u32,
    pub consumed: u32,
    pub ignored: u32,
    pub active_pointer_id: Option<u32>,
    pub pointer_down: bool,
    pub ui_attempts: u32,
    pub ui_dispatched: u32,
    pub cocos_attempts: u32,
    pub cocos_dispatched: u32,
    pub last_phase: Option<String>,
    pub last_target: Option<u32>,
    pub last_x: Option<f32>,
    pub last_y: Option<f32>,
    pub last_dispatch: Option<String>,
    pub last_source: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RuntimeNetworkSummary {
    pub url: String,
    pub host: String,
    pub path: String,
    pub method: String,
    pub payload_len: u32,
    pub state_code: u32,
    pub state: String,
    pub armed: bool,
    pub completed: bool,
    pub faulted: bool,
    pub cancelled: bool,
    pub timeout_armed: bool,
    pub source_closed: bool,
    pub stage: u32,
    pub events: u32,
    pub delegate_callbacks: u32,
    pub bytes_delivered: u32,
    pub retained_response: bool,
    pub retained_data: bool,
    pub retained_error: bool,
    pub fault_events: u32,
    pub fault_mode: u32,
    pub fault_modes: Vec<String>,
    pub last_error_domain: Option<String>,
    pub last_error_code: Option<i32>,
    pub last_error_kind: Option<String>,
    pub last_error_description: Option<String>,
    pub retry_recommended: bool,
    pub foundation_string_backing: bool,
    pub foundation_data_backing: bool,
    pub data_bytes_ptr: Option<u32>,
    pub payload_preview_ascii: String,
    pub delegate_binding_trace: Vec<String>,
    pub connection_birth_trace: Vec<String>,
    pub slot_trace: Vec<String>,
    pub owner_candidate_trace: Vec<String>,
    pub last_delegate_binding: Option<String>,
    pub last_connection_birth: Option<String>,
    pub last_slot_event: Option<String>,
    pub last_owner_candidate: Option<String>,
    pub first_app_delegate_binding: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RuntimeReachabilitySummary {
    pub scheduled: bool,
    pub callback_set: bool,
    pub flags: u32,
    pub flags_label: String,
    pub state: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RuntimeStreamSummary {
    pub read_status_code: u32,
    pub read_status: String,
    pub read_open: bool,
    pub read_scheduled: bool,
    pub read_client_set: bool,
    pub read_events: u32,
    pub read_bytes_consumed: u32,
    pub read_has_bytes_available: bool,
    pub write_status_code: u32,
    pub write_status: String,
    pub write_open: bool,
    pub write_scheduled: bool,
    pub write_client_set: bool,
    pub write_events: u32,
    pub write_bytes_written: u32,
    pub write_can_accept_bytes: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RuntimeGraphicsSummary {
    pub api: String,
    pub context_current: bool,
    pub layer_attached: bool,
    pub surface_ready: bool,
    pub framebuffer_complete: bool,
    pub viewport_ready: bool,
    pub presented: bool,
    pub readback_ready: bool,
    pub frame_index: u32,
    pub present_calls: u32,
    pub draw_calls: u32,
    pub clear_calls: u32,
    pub readback_calls: u32,
    pub gl_calls: u32,
    pub last_error: u32,
    pub surface_width: u32,
    pub surface_height: u32,
    pub viewport_x: u32,
    pub viewport_y: u32,
    pub viewport_width: u32,
    pub viewport_height: u32,
    pub scissor_enabled: bool,
    pub scissor_x: u32,
    pub scissor_y: u32,
    pub scissor_width: u32,
    pub scissor_height: u32,
    pub framebuffer_bytes: u32,
    pub last_readback_bytes: u32,
    pub last_readback_x: u32,
    pub last_readback_y: u32,
    pub last_readback_width: u32,
    pub last_readback_height: u32,
    pub last_readback_checksum: u32,
    pub last_readback_origin: Option<String>,
    pub last_present_source: Option<String>,
    pub last_present_decision: Option<String>,
    pub last_visible_bbox_x: u32,
    pub last_visible_bbox_y: u32,
    pub last_visible_bbox_width: u32,
    pub last_visible_bbox_height: u32,
    pub last_visible_pixels: u32,
    pub last_nonzero_pixels: u32,
    pub diagnosis_hint: Option<String>,
    pub recent_events: Vec<String>,
    pub readback_changed: bool,
    pub readback_stable_streak: u32,
    pub dominant_rgba: Option<String>,
    pub dominant_pct_milli: u32,
    pub unique_frames_saved: u32,
    pub last_unique_dump_path: Option<String>,
    pub retained_present_calls: u32,
    pub synthetic_fallback_present_calls: u32,
    pub auto_scene_present_calls: u32,
    pub guest_draw_calls: u32,
    pub guest_vertex_fetches: u32,
    pub last_draw_mode: u32,
    pub last_draw_mode_label: Option<String>,
    pub last_guest_draw_checksum: u32,
    pub uikit_context_current: bool,
    pub uikit_contexts_created: u32,
    pub uikit_images_created: u32,
    pub uikit_draw_ops: u32,
    pub uikit_present_ops: u32,
    pub last_ui_source: Option<String>,
    pub dump_frames_enabled: bool,
    pub dump_every: u32,
    pub dump_limit: u32,
    pub dumps_saved: u32,
    pub last_dump_path: Option<String>,
    pub last_raw_dump_path: Option<String>,
    pub last_bgra_dump_path: Option<String>,
    pub last_viewport_tl_dump_path: Option<String>,
    pub last_viewport_bl_dump_path: Option<String>,
    pub last_bbox_dump_path: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RuntimeSceneSummary {
    pub transition_calls: u32,
    pub run_with_scene_calls: u32,
    pub replace_scene_calls: u32,
    pub push_scene_calls: u32,
    pub on_enter_events: u32,
    pub on_exit_events: u32,
    pub on_enter_transition_finish_events: u32,
    pub running_scene_ticks: u32,
    pub menu_probe_attempts: u32,
    pub menu_probe_fired: bool,
    pub recent_events: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RuntimeSchedulerSummary {
    pub mainloop_calls: u32,
    pub draw_scene_calls: u32,
    pub draw_frame_calls: u32,
    pub schedule_calls: u32,
    pub update_calls: u32,
    pub invalidate_calls: u32,
    pub render_callback_calls: u32,
    pub recent_events: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RuntimeUiTreeNodeSample {
    pub ptr: u32,
    pub label: String,
    pub parent: u32,
    pub parent_label: Option<String>,
    pub child_count: u32,
    pub raw_texture: u32,
    pub texture: u32,
    pub texture_key: Option<String>,
    pub position_x: f32,
    pub position_y: f32,
    pub world_x: f32,
    pub world_y: f32,
    pub raw_width: u32,
    pub raw_height: u32,
    pub width: u32,
    pub height: u32,
    pub anchor_x: f32,
    pub anchor_y: f32,
    pub anchor_explicit: bool,
    pub visible: bool,
    pub entered: bool,
    pub touch_enabled: bool,
    pub draw_eligible: bool,
    pub draw_reason: String,
    pub texture_rect_explicit: bool,
    pub texture_rect_x: f32,
    pub texture_rect_y: f32,
    pub texture_rect_w: f32,
    pub texture_rect_h: f32,
    pub callback_selector: Option<String>,
    pub text_backing: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RuntimeUiTreeSummary {
    pub running_scene: u32,
    pub total_nodes: u32,
    pub reachable_nodes: u32,
    pub detached_nodes: u32,
    pub visible_nodes: u32,
    pub entered_nodes: u32,
    pub textured_nodes: u32,
    pub visible_textureless_nodes: u32,
    pub menu_nodes: u32,
    pub menu_item_nodes: u32,
    pub label_nodes: u32,
    pub touch_enabled_nodes: u32,
    pub callback_nodes: u32,
    pub sampled_nodes: Vec<RuntimeUiTreeNodeSample>,
    pub detached_sampled_nodes: Vec<RuntimeUiTreeNodeSample>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RuntimeCountEntry {
    pub name: String,
    pub count: u32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RuntimeBackendStopSite {
    pub trap_class: String,
    pub pc: u32,
    pub thumb: bool,
    pub count: u32,
    pub symbol: Option<String>,
    pub reason: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RuntimeBackendSemanticsCandidate {
    pub area: String,
    pub total_hits: u32,
    pub weighted_score: u32,
    pub evidence: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RuntimeFilesystemSummary {
    pub bundle_available: bool,
    pub bundle_root: Option<String>,
    pub indexed_files: u32,
    pub cached_images: u32,
    pub bundle_objects_created: u32,
    pub bundle_scoped_hits: u32,
    pub bundle_scoped_misses: u32,
    pub png_cgbi_detected: u32,
    pub png_cgbi_decoded: u32,
    pub png_decode_failures: u32,
    pub image_named_hits: u32,
    pub image_named_misses: u32,
    pub file_open_hits: u32,
    pub file_open_misses: u32,
    pub file_read_ops: u32,
    pub file_bytes_read: u32,
    pub open_file_handles: u32,
    pub last_resource_name: Option<String>,
    pub last_resource_path: Option<String>,
    pub last_file_path: Option<String>,
    pub last_file_mode: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RuntimeHeapSummary {
    pub base: u32,
    pub end: u32,
    pub cursor: u32,
    pub allocations_total: u32,
    pub allocations_active: u32,
    pub frees: u32,
    pub reallocs: u32,
    pub bytes_active: u32,
    pub bytes_peak: u32,
    pub bytes_reserved: u32,
    pub last_alloc_ptr: Option<u32>,
    pub last_alloc_size: Option<u32>,
    pub last_freed_ptr: Option<u32>,
    pub last_realloc_old_ptr: Option<u32>,
    pub last_realloc_new_ptr: Option<u32>,
    pub last_realloc_size: Option<u32>,
    pub last_error: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RuntimeVfpSummary {
    pub multi_ops: u32,
    pub load_multi_ops: u32,
    pub store_multi_ops: u32,
    pub pc_base_ops: u32,
    pub pc_base_load_ops: u32,
    pub pc_base_store_ops: u32,
    pub single_reg_capacity: u32,
    pub single_range_ops: u32,
    pub exact_opcode_hits: u32,
    pub exact_override_hits: u32,
    pub single_transfer_ops: u32,
    pub double_transfer_ops: u32,
    pub last_op: Option<String>,
    pub last_start_addr: Option<u32>,
    pub last_end_addr: Option<u32>,
    pub last_pc_base_addr: Option<u32>,
    pub last_pc_base_word: Option<u32>,
    pub last_single_range: Option<String>,
    pub last_exact_opcode: Option<String>,
    pub last_exact_decoder_branch: Option<String>,
    pub last_transfer_mode: Option<String>,
    pub last_transfer_start_reg: Option<u32>,
    pub last_transfer_end_reg: Option<u32>,
    pub last_transfer_count: Option<u32>,
    pub last_transfer_precision: Option<String>,
    pub last_transfer_addr: Option<u32>,
    pub last_exact_reason: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RuntimeArmSummary {
    pub reg_shift_operand2_ops: u32,
    pub extra_load_store_ops: u32,
    pub extra_load_store_loads: u32,
    pub extra_load_store_stores: u32,
    pub last_reg_shift: Option<String>,
    pub last_extra_load_store: Option<String>,
    pub exact_epilogue_site_hits: u32,
    pub exact_epilogue_repairs: u32,
    pub exact_epilogue_last_pc: Option<u32>,
    pub exact_epilogue_last_before_sp: Option<u32>,
    pub exact_epilogue_last_after_sp: Option<u32>,
    pub exact_epilogue_last_r0: Option<u32>,
    pub exact_epilogue_last_r7: Option<u32>,
    pub exact_epilogue_last_r8: Option<u32>,
    pub exact_epilogue_last_lr: Option<u32>,
    pub exact_epilogue_last_repair: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RuntimeObjcBridgeSummary {
    pub metadata_available: bool,
    pub classlist_present: bool,
    pub cfstring_present: bool,
    pub parsed_classes: u32,
    pub delegate_name: Option<String>,
    pub delegate_class_name: Option<String>,
    pub inferred_class_name: Option<String>,
    pub inferred_selector_hits: u32,
    pub launch_selector: Option<String>,
    pub launch_imp: Option<u32>,
    pub bridge_attempted: bool,
    pub bridge_succeeded: bool,
    pub failure_reason: Option<String>,
    pub real_msgsend_dispatches: u32,
    pub last_real_selector: Option<String>,
    pub super_msgsend_dispatches: u32,
    pub super_msgsend_fallback_returns: u32,
    pub last_super_selector: Option<String>,
    pub last_super_receiver: Option<u32>,
    pub last_super_class: Option<u32>,
    pub last_super_imp: Option<u32>,
    pub alloc_calls: u32,
    pub alloc_with_zone_calls: u32,
    pub class_create_instance_calls: u32,
    pub init_calls: u32,
    pub instances_materialized: u32,
    pub last_alloc_class: Option<String>,
    pub last_alloc_receiver: Option<u32>,
    pub last_alloc_result: Option<u32>,
    pub last_init_receiver: Option<u32>,
    pub last_init_result: Option<u32>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RuntimeHotPathSummary {
    pub objc_msgsend_calls: u32,
    pub objc_unique_selectors: u32,
    pub recent_objc_selectors: Vec<String>,
    pub top_objc_selectors: Vec<RuntimeCountEntry>,
    pub saw_draw_rect: bool,
    pub saw_set_needs_display: bool,
    pub saw_layout_subviews: bool,
    pub saw_image_named: bool,
    pub saw_present_renderbuffer: bool,
    pub gl_calls_seen: u32,
    pub recent_gl_calls: Vec<String>,
    pub top_gl_calls: Vec<RuntimeCountEntry>,
    pub saw_gl_bind_texture: bool,
    pub saw_gl_teximage2d: bool,
    pub saw_gl_draw_arrays: bool,
    pub saw_gl_draw_elements: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RuntimeObservabilitySummary {
    pub trace_build_id: String,
    pub trace_banner_emitted: bool,
    pub scene_progress_trace: Vec<String>,
    pub sprite_watch_trace: Vec<String>,
    pub graph_trace: Vec<String>,
    pub scheduler_trace: Vec<String>,
    pub scheduler_trace_live_snapshot: String,
    pub callback_trace: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RuntimeAudioSummary {
    pub openal_device_open_calls: u32,
    pub openal_context_create_calls: u32,
    pub openal_make_current_calls: u32,
    pub openal_buffers_generated: u32,
    pub openal_sources_generated: u32,
    pub openal_buffer_upload_calls: u32,
    pub openal_bytes_uploaded: u64,
    pub openal_queue_calls: u32,
    pub openal_unqueue_calls: u32,
    pub openal_play_calls: u32,
    pub openal_stop_calls: u32,
    pub openal_last_buffer_format: Option<String>,
    pub openal_last_source_state: Option<String>,
    pub audioqueue_create_calls: u32,
    pub audioqueue_allocate_calls: u32,
    pub audioqueue_enqueue_calls: u32,
    pub audioqueue_enqueued_bytes: u64,
    pub audioqueue_prime_calls: u32,
    pub audioqueue_start_calls: u32,
    pub audioqueue_stop_calls: u32,
    pub audioqueue_dispose_calls: u32,
    pub audioqueue_output_callback_dispatches: u32,
    pub audioqueue_property_callback_dispatches: u32,
    pub audioqueue_last_format: Option<String>,
    pub audioqueue_last_queue: Option<u32>,
    pub audioqueue_last_buffer: Option<u32>,
    pub audioqueue_last_buffer_preview_hex: Option<String>,
    pub audioqueue_last_buffer_preview_ascii: Option<String>,
    pub audiofile_open_calls: u32,
    pub audiofile_read_bytes_calls: u32,
    pub audiofile_read_packets_calls: u32,
    pub audiofile_bytes_served: u64,
    pub systemsound_create_calls: u32,
    pub systemsound_play_calls: u32,
    pub systemsound_dispose_calls: u32,
    pub objc_audio_player_alloc_calls: u32,
    pub objc_audio_player_init_url_calls: u32,
    pub objc_audio_player_init_data_calls: u32,
    pub objc_audio_player_prepare_calls: u32,
    pub objc_audio_player_play_calls: u32,
    pub objc_audio_player_pause_calls: u32,
    pub objc_audio_player_stop_calls: u32,
    pub objc_audio_player_set_volume_calls: u32,
    pub objc_audio_player_set_loops_calls: u32,
    pub objc_audio_engine_shared_calls: u32,
    pub objc_audio_manager_shared_calls: u32,
    pub objc_audio_manager_soundengine_calls: u32,
    pub objc_audio_manager_soundengine_nil_results: u32,
    pub objc_audio_engine_preload_calls: u32,
    pub objc_audio_bgm_preload_calls: u32,
    pub objc_audio_engine_play_calls: u32,
    pub objc_audio_bgm_play_calls: u32,
    pub objc_audio_engine_stop_calls: u32,
    pub objc_audio_engine_effect_calls: u32,
    pub objc_audio_engine_async_load_progress_calls: u32,
    pub objc_audio_engine_async_load_progress_nil_receivers: u32,
    pub objc_audio_engine_playsound_calls: u32,
    pub objc_audio_engine_playsound_nil_receivers: u32,
    pub objc_audio_fallback_dispatches: u32,
    pub objc_audio_last_class: Option<String>,
    pub objc_audio_last_selector: Option<String>,
    pub objc_audio_last_resource: Option<String>,
    pub objc_audio_last_result: Option<String>,
    pub objc_audio_last_call_args: Option<String>,
    pub objc_audio_last_scalar_probe: Option<String>,
    pub unsupported_events: u32,
    pub recent_events: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RuntimeBackendExecutionSummary {
    pub backend_policy: String,
    pub total_steps: u64,
    pub native_steps: u64,
    pub shadow_steps: u64,
    pub shadow_trap_steps: u64,
    pub shadow_fallback_steps: u64,
    pub shadow_handoff_steps: u64,
    pub trap_dispatches: u32,
    pub fallback_dispatches: u32,
    pub handoff_count: u32,
    pub native_share_milli: u32,
    pub shadow_share_milli: u32,
    pub trap_classes: Vec<RuntimeCountEntry>,
    pub top_stop_sites: Vec<RuntimeBackendStopSite>,
    pub semantics_candidates: Vec<RuntimeBackendSemanticsCandidate>,
    pub last_trap_class: Option<String>,
    pub last_trap_reason: Option<String>,
    pub last_handoff_reason: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RuntimeStateReport {
    pub synthetic: RuntimeSyntheticConfigReport,
    pub ui: RuntimeUiSummary,
    pub runloop: RuntimeRunloopSummary,
    pub input: RuntimeInputSummary,
    pub network: RuntimeNetworkSummary,
    pub reachability: RuntimeReachabilitySummary,
    pub streams: RuntimeStreamSummary,
    pub graphics: RuntimeGraphicsSummary,
    pub scene: RuntimeSceneSummary,
    pub scheduler: RuntimeSchedulerSummary,
    pub ui_tree: RuntimeUiTreeSummary,
    pub filesystem: RuntimeFilesystemSummary,
    pub heap: RuntimeHeapSummary,
    pub vfp: RuntimeVfpSummary,
    pub arm: RuntimeArmSummary,
    pub objc_bridge: RuntimeObjcBridgeSummary,
    pub hot_path: RuntimeHotPathSummary,
    pub observability: RuntimeObservabilitySummary,
    pub audio: RuntimeAudioSummary,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RuntimeReport {
    pub backend: String,
    pub mapped_regions: usize,
    pub registered_stubs: usize,
    pub entry_pc: u32,
    pub initial_sp: u32,
    pub memory_writes: usize,
    pub first_instruction_addr: Option<u32>,
    pub first_instruction: Option<u32>,
    pub first_instruction_text: Option<String>,
    pub entry_bytes_present: bool,
    pub executed_instructions: u64,
    pub final_pc: Option<u32>,
    pub final_sp: Option<u32>,
    pub final_lr: Option<u32>,
    pub stop_reason: String,
    pub trace: Vec<String>,
    pub status: String,
    pub runtime_state: Option<RuntimeStateReport>,
    pub backend_execution: Option<RuntimeBackendExecutionSummary>,
}
